import "./globals.css";
import { Montserrat, Roboto, Nanum_Gothic } from "next/font/google";
import Navbar from "./components/Navbar";
import Main from "./components/Main";
import About from "./components/About";
import Skills from "./components/Skills";
import Projects from "./components/Project";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mont" });
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-robo",
  weight: ["100", "300", "400", "500", "700", "900"],
});
const nanum = Nanum_Gothic({
  weight: ["400", "700", "800"],
  subsets: ["latin"],
  variable: "--font-nanum",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`text-dark ${montserrat.variable} ${roboto.variable} ${nanum.variable}`}
      >
        <Navbar />
        <Main />
        <About />
        <Skills />
        <Projects />
        {children}
      </body>
    </html>
  );
}
